/**
 * Sesión REMPe
 * Servicio de integración para sistemas externos con la interfaz de REMPe. Proporciona alos sistemas externos que quieran integrarse con REMPe las herramientas necesarias para acceder a la interfaz de REMPe directamente por parte de sus profesionales.  El sistema externo se hace responsable de la identificación del profesional y la unidad.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: soporterempe@drimay.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Dirección postal. Se utilizan los datos del INE para la codificación territorial.
 */
export class Address {
  /**
   * Representación de la dirección
   */
  'text'?: string;
  /**
   * Lineas de la dirección en orden en el que aparecerán. Nombre de la calle, número, dirección, código postal, etc.
   */
  'line'?: Array<string>;
  /**
   * Código postal
   */
  'postalCode'?: string;
  /**
   * Nombre del municipio. Si no se marca el municipalityCode y si se rellena este campo se buscará un municipio con el nombre descrito (nombre del INE http://www.ine.es/daco/daco42/codmun/codmunmapa.htm).
   */
  'cityName'?: string;
  /**
   * Código del municipio. Se utilizará la codificación del INE. http://www.ine.es/daco/daco42/codmun/codmunmapa.htm
   */
  'cityCode'?: string;
  /**
   * Nombre de la provincia. Si no se marca el cityCode y si se rellena este campo se buscará una provincia con el nombre descrito (nombre INE http://www.ine.es/daco/daco42/codmun/cod_provincia.htm)
   */
  'districtName'?: string;
  /**
   * Código de la provincia. Se utilizará la codificación del INE. http://www.ine.es/daco/daco42/codmun/cod_provincia.htm
   */
  'districtCode'?: string;
  /**
   * Nombre de la región o comunidad autónoma. Si no se marca el regionCode y si se rellena este campo se buscará una comunidad con el nombre descrito (nombre INE http://www.ine.es/daco/daco42/codmun/cod_ccaa.htm)
   */
  'stateName'?: string;
  /**
   * Código de la región o comunidad autónoma. Se utilizará la codificación del INE. http://www.ine.es/daco/daco42/codmun/cod_ccaa.htm
   */
  'stateCode'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'text',
      baseName: 'text',
      type: 'string',
      format: '',
    },
    {
      name: 'line',
      baseName: 'line',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'postalCode',
      baseName: 'postalCode',
      type: 'string',
      format: '',
    },
    {
      name: 'cityName',
      baseName: 'cityName',
      type: 'string',
      format: '',
    },
    {
      name: 'cityCode',
      baseName: 'cityCode',
      type: 'string',
      format: '',
    },
    {
      name: 'districtName',
      baseName: 'districtName',
      type: 'string',
      format: '',
    },
    {
      name: 'districtCode',
      baseName: 'districtCode',
      type: 'string',
      format: '',
    },
    {
      name: 'stateName',
      baseName: 'stateName',
      type: 'string',
      format: '',
    },
    {
      name: 'stateCode',
      baseName: 'stateCode',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return Address.attributeTypeMap;
  }

  public constructor() {}
}
