/**
 * Nomenclator REMPe
 * Servicio de catálogo e productos
 *
 * OpenAPI spec version: 2.0.0
 * Contact: soporterempe@drimay.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Tipo de objeto en el nomenclator.
 */
export type NomenclatorType = 'MEDICINE' | 'PRODUCT' | 'MASTER_FORMULA' | 'DIETOTERAPICO' | 'MEDICAL_DEVICES';
